name: Seleccion de entornos

on:
 workflow_call:
  outputs: 
   entorno:
    value: ${{jobs.entorno.outputs.entorno}}

jobs:
 entorno:
  runs-on: ubuntu-latest
  outputs:
   entorno: ${{steps.entorno.outputs.entorno}}
  steps:
  - name: Elegir entorno
    id: entorno
    run: |
     if [github.ref == 'refs/heads/main']; then
      echo ENTORNO="producciÃ³n" >> GITHUB_ENV
      echo "entorno=$ENTORNO" >> GITHUB_OUTPUT
     elif [github.ref == 'refs/heads/development']; then
      echo ENTORNO="UAT" >> GITHUB_ENV
      echo "entorno=$ENTORNO" >> GITHUB_OUTPUT
     fi